### ISSUE TITLE
vts password

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-backend#12]
feeling a little sheepish here, but what is the password for the 'vts' user created when installing vts-backend? Can't figure it out and don't see documentation about it either...

**Comment by vaclavblazek** [comment]
From `vts-backend`'s `postinst` script:
```
adduser \
            --ingroup ${USER} \
            --no-create-home \
            --disabled-password \
            --home "${HOME}" \
            --gecos "VTS user" \
            --shell /bin/bash \
            ${USER} >/dev/null
```
So, there is no password. You can switch to this account via switching to root first (`sudo -s vts`).

Or, for convenience, you can add your ssh key to `~vts/.ssh/authorized_keys` file (note that vts user home is `/var/vts/`!) and then you can ssh to `vts@machine`. You have to set proper mode (600 for file and 700 for dir) and proper dir ownership (vts:vts).

Or you can enable just password, if this is your local machine. Use `sudo passwd vts` and enter your new password.

**Comment by jrjdavidson** [comment]
Thanks- didn't think of that last one... Sorry, a bit new to all this!
