### ISSUE TITLE
store generation helper function

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-backend#13]
I'm struggling a bit with the creation of store views. Just as an offchance, is there a helper funtion to create store views? (similar to mapproxy-setup-resource) 

Also - I was able to create a a bound layer using tms-raster-remote that works great, but I'm scratching my head as to how I should add it as a store view. at the moment i define it in the resources.json file, and can call it by group and id.

**Comment by jrjdavidson** [comment]
I've been banging my head on this one and can't seem to find out what I'm doing wrong. I've built the following store file below, the vts --map-config generates a json file that looks reasonable, but I can't get a good result.

`
{
      "storage": "../stage.melown2015",
      "tilesets": ["DEM-worldJdF","DEM-icelandJdF"],
      "credits": {},
      "boundLayers": {
	},
      "freeLayers": {},
      "view": {
              "description": "",
              "surfaces": {
                      "DEM-worldJdF": [""]
              },
              "freeLayers": {}
      },
      "namedViews": {},
      "position": [
              "obj",170,-45,"float",0.00,3.16,-70.91,0.00,226.97,45.00
      ],
      "version": 1
}
`
Here is the result
https://vtsbackend.canterbury.ac.nz/store/map-config/world

**Comment by vaclavblazek** [comment]
Since browser is trying to fetch this metatile:
`http://127.0.0.1:8070/mapproxy/melown2015/surface/DEM/worldJdF/0-0-0.meta?0`
it seems you added tileset with host-local url.

**Comment by jrjdavidson** [comment]
Yes I did. Thanks!
