### ISSUE TITLE
General question about LOD on surfaces and bound Layers

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-backend#14]
I've been experimenting with various surfaces and bounlayers, and it appears to me that a surface will not display higher LOD boundlayers than the surface has. 

for example, this surface was generated using mapproxy-setup-resource, without specifying a bottomLOD, and if you zoom in it goes to LOD 11:
https://vtsbackend.canterbury.ac.nz/mapproxy/melown2015/surface/DEM/worldJdF/?pos=obj,172.710177,-43.556349,fix,142.73,-45.01,-53.35,0.00,21771.04,45.00
However the boundlayer can generate a much higher LOD: 
https://vtsbackend.canterbury.ac.nz/mapproxy/melown2015/tms/linz/lds-ophoto/

When generating a surface, should I always specify the highest LOD level that i expect a boundlayer to be, using the --bottomLOD argument? It seems like a bit of a waste?

**Comment by vaclavblazek** [comment]
Bottom LOD is only for **surfaces** and only used for one specific thing: when merging various datasources this says: you do not get any detail going past this LOD.

**Comment by jrjdavidson** [comment]
Thanks for your answer vaclav, but I'm still little bit confused.
With the example I gave above, should I reprocess the surface "worldjdf" to a higher lod so I am able to see the detial of boundlayer? What do I have to do to see a lod level higher than 11 on bound layers that are displayed on the 'worldjdf' surface ( as that surface only goes to 11)?

**Comment by vaclavblazek** [comment]
> When generating a surface, should I always specify the highest LOD level that i expect a boundlayer to be, using the --bottomLOD argument? It seems like a bit of a waste?

Oh, I missed the question. Yes, you need something to put the boundlayer on. There is currently no way how to glue more detailed BL on coarser mesh.

**Comment by jrjdavidson** [comment]
Ok thanks, so I'll use the bottomlod argument to generate the right lod level on the surface, based on the boundlayers I wish to display.

**Comment by vaclavblazek** [comment]
No, forget bottom LOD, it's a for merging optimization. You do not need it unless you are merging huge deep datasets together. Just make the lodRange of both boundlayer and surface the same.

**Comment by jrjdavidson** [comment]
where/when do I set the lod range when running mapproxy-setup-resource?

**Comment by vaclavblazek** [comment]
Ooops. My bad. Sorry. Naming clash. I forgot about how setup resource works. Of course, this is the right `--bottomLod`. My head was stuck with the other bottomLod...

Just specify the bottomLod the same for both datasets.
