### ISSUE TITLE
sudo apt install vts-backend has unmet dependencies

### ISSUE THREAD

**Issue by ajinra020307** [Melown/vts-backend#16]
When trying to install vts-backend using apt

`sudo apt install vts-backend`

`The following packages have unmet dependencies:
 vts-backend : Depends: vts-mapproxy (>= 1.53) but it is not going to be installed
               Depends: vts-mapproxy-tools but it is not going to be installed
               Depends: vts-tools (>= 1.82) but it is not going to be installed
               Depends: vts-vtsd (>= 1.31) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

Iam running in debian 10

**Comment by vaclavblazek** [comment]
We do not provide public packages for debian 10 (buster). You are probably trying to install ubuntu packages on debian.
