### ISSUE TITLE
classes / media queries for geodata styling?

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-backend#18]
Hi
I was trying to think how I could dynamically change the styling of geodata. If the styling was html/css, I would probably create a class and add the class to the element when the style change was necessary. How would you go about it for geodata?

I also had a quick look in the docs for something similar to media queries in geodata styling but couldn't find anything. Any tricks that work like `@media (hover: hover) { //style here..}`.

**Comment by ladislavhorky** [comment]
Hi, could you please move this issue to https://github.com/melowntech/vts-browser-js ? Styling it exclusively @davidmtech 's playfield :) ... I think it is more carto-css _inpired_ - completely internal to VTS, no functional relation to html as I am aware. But it is possible to change the style in API, so some dynamics should be possible too.

**Comment by jrjdavidson** [comment]
Woops,I meant to put it there
