### ISSUE TITLE
Duplicate of storage?

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-backend#21]
Hi guys, 

Looking for some advice on duplicating a storage stack. I currently have the melown2015 storage being used in a course, but would like to modify it, remove some surfaces and add others. This will take quite some time as the glues are huge. I obviously don't want to play with the storage while in production, so thought it might be useful to duplicate the storage, modify it, and then replace the old storage with the new. 

Any thoughts how to do this? Is it as simple as duplicating the folder in the /var/vts/store/ ( surely not)? Or is there something similar to `/etc/init.d/vts-backend-mapproxy stop` 

Cheers

**Comment by vaclavblazek** [comment]
Hi,

`vtsd` (not `mapproxy`, which is dynamic surface generator) does not care how directories are named or how deep they are. It opens anything that looks like a valid dataset (tileset/storage/storageview). You can have any number of datasets anywhere your `vtsd` looks for them. `vtsd` works kinda like `nginx` -- you map a location (i.e. URL) to a filesystem path, either using the exact string match or via a regex match.

For example, you can have one location browsable ("list dir") with the built-in browser (with `index.html`) and another without, even mapping to the same filesystem path. Or any other configuration, like in `nginx`.

The stock `vtsd` config in `vts-backend` (i.e. `/etc/vts/vtsd/vtsd.conf`) maps location `/` to path `/var/vts/store` (with the exception of `/stylesheet` location that is handled differently). Anything placed under this path is seen by the default-configured `vts-backend`.

You can either copy the storage to another path or create a brand new (clean) storage with `vts /path/to/storage --create --referenceFrame melown2015`. No need to restart `vtsd`, it even tests datasets for change (selected files, like `tileset.conf`, `storage.conf` etc., not all files).

BTW, storages can even use tilesets from another storages (via `local` tileset type).  You can even have an aggegated tileset that presents a storage view as an opaque tileset that can be referenced in another storage.

Re huge glues: you can even control what tilesets can be merged (glued) together. For example, if you have multiple world-wide datasets you may configure the storage so these are not merged together (no glues generated), it needs a bit of configuration.
Or you may have different versions of the same tileset where it makes no sense to glue them together (which is done easily via tileset versioning). So there can be one live version presented to the user while you can mess with another version and then switch them. Switching requires more configureation, tho.

(You may have noticed I used both `surface` and `tilestet` terms: `surface` is a frontend concept while `tileset` is a backend/data storage concept. For example, mapproxy generates surfaces on the fly from some non-VTS data while there is no tileset stored on the disk. On the other hand, a mapproxy-generated surface can be used as a remote tileset.)

**Comment by jrjdavidson** [comment]
Thanks for all the information Vaclav, I will give it a try and let you know if I have any issues.
