### ISSUE TITLE
data on seperate drive?

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-backend#26]
I was thining that it would be handy to have all processed data on a seperate drive from the OS drive that can be easily mounted/unmounted as data is updated (e.g I might set up a seperate dev and production server).
As far as I can tell, all changes to the data occurs on /etc/vts and /var/vts when it is processed for vts. How would you go about it, if say I wanted to store the data generated on a drive mounted, for example on /datadrive/...? Is it easy to change, or not worth the effort?

Cheers

**Comment by vaclavblazek** [comment]
We do this in ourselves. All relevant data are moved to mounted data drive and original path is replaced with a symlink to new location.

For example, we have a data drive mounted at `/mnt/vts` and original paths replaced with symlinks:
```
lrwxrwxrwx 1 vts vts 21 May  4 10:45 /etc/vts/mapproxy -> /mnt/vts/etc/mapproxy
lrwxrwxrwx 1 vts vts 17 May  4 10:41 /var/vts/mapproxy -> /mnt/vts/mapproxy
```

**Comment by jrjdavidson** [comment]
Too easy, will give it a try, thanks! In your example, you link the contents of the mapproxy folder, wouldn't be easier to copy the full contents of /etc/vts/ and /var/vts, that way you capture the storage, glues and other data as well?

**Comment by vaclavblazek** [comment]
Oh, yes, we copy/move them too and link as well. I grabbed the links above from a machine where it's done a bit differently.
