### ISSUE TITLE
mask for wmts service?

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-backend#30]
Sorry for bombarding you with requests.. Any tips or resources available somewhere on how to produce a mask for a bound surface that is served through WMTS? I had a quick look around the git repository and couldn't find anything specific apart for link to esri mask tool. I do have access the arc, but not sure how I would set it up once it's been generated.

 I'd like to mask a dataset to the coastline of NZ, see here:
![image](https://user-images.githubusercontent.com/46798391/132766142-2b723c58-84b6-415f-b1bc-e850bd3b00c3.png)

**Comment by vaclavblazek** [comment]
You probably mean bound layer, not bound surface.

We support external mask in two formats: 
 * raster (i.e. image) -- which should have overviews
 * our special mask format (quadtree)

Both mask types can be specified via `mask` option in resource definition -- path relative to dataset root.

If you've gota WMTS dataset that acts as a validity mask (single channel image, 0=invalid, >0=valid) you can create a GDAL resource XML WMTS file for it ([reference](https://gdal.org/drivers/raster/wmts.html)).

Or, you can convert a vector dataset (geojson, shapefile, ...) to the above mentioned quadtree format via `mapproxy-rf-mask` tool (from `vts-mapproxy-tools` package). I've used it to generate masks for various countries from OSM county border datasets; we used it to stack much detailed Czech and Austrian ortophoto maps over global imagery.

**Comment by jrjdavidson** [comment]
Yes i meant bound layer! 
The latter seems to be exactly what I need. I've launched the rf-mask tool, using a shapefile, how do I use the output to mask a dataset?

**Comment by vaclavblazek** [comment]
Just extend your **raster** resources definition, e.g.:
```
definition {
    "dataset": "path-to-dataset",
    "mask":"path-to-your-mask-file
    ...
}
```
NB: Path to `mask` is relative to dataset root from mapproxy configuration (unless the path is absolute, ofc), the same way as `dataset` is.
NB: When you use more bound layers on a surface the bound layer stack's top is the last entry.

BTW, mapproxy resource's are documented the  [mapproxy](https://github.com/melowntech/vts-mapproxy/blob/master/docs/resources.md) repo.

**Comment by jrjdavidson** [comment]
Thanks for the link to the documentation, I had no idea it was there! It's really useful.
I created a mask from a NZ polygon, lod 17. Took a while but seem to work. Got this message at the end though: 

2021-09-10 20:45:20 I3 [178687(5)]: Processed blocks progress:  99.99 %. {progress.cpp:report():101}
2021-09-10 20:45:22 I3 [178687(main)]: Converting input into <steren-wgs84>. {main.cpp:rasterize():595}
2021-09-10 20:45:39 I3 [178687(main)]: No data in node 1-0-1 (srs: steren-wgs84). {main.cpp:rasterize():603}
2021-09-10 20:45:39 I3 [178687(main)]: Converting input into <steres-wgs84>. {main.cpp:rasterize():595}
2021-09-10 20:45:57 I3 [178687(main)]: No data in node 1-1-0 (srs: steres-wgs84). {main.cpp:rasterize():603}
2021-09-10 20:45:57 I3 [178687(main)]: Saving output to "mask". {main.cpp:run():705}


I tried adding it to a dataset anyways, and it looks like mapproxy or gdal is looking for a specific file:

gdal error 4:  not recognized as a supported file format. {geodataset.cpp:GDALErrorHandler():77}

 - did I have to save it with a particular extension?

**Comment by vaclavblazek** [comment]
Pls, can you paste here your resorce JSON and send me the generated mask file?

**Comment by jrjdavidson** [comment]
I tried to mask both a surface and the remote boundlayer, I realised the error message is different for the surface. I had tried the bound layer first, but realised that the docs specifically reference the mapproxy-rf-mask tool on the surface-dem driver whereas raster remote only says 'rf mask'. the error message for the surface is different, it says: 
`Failed to create generator for resource <melown2015/linz/NZ8mDEMv3masked>: <basic_ios::clear: iostream error>.`
here are the json files I used, will send a link to file via email: 

        , {
		"comment": "lds orthophoto",
		"group": "linz",
		"id": "lds-ophoto4",
		"type": "tms",
		"driver": "tms-raster-remote",
		"credits": ["linz"],
		"definition": {
			"remoteUrl": "https://basemaps.linz.govt.nz/v1/tiles/aerial/EPSG:3857/{loclod}/{locx}/{locy}.webp?api=xx",
	    		"mask":"Nz.mask/mask"
		},
		"registry": {
			"credits" : {"linz":{ "id": 99, "notice": "<a href=http://data.linz.govt.nz target=_blank>Sourced from LINZ. CC BY 4.0</a>" }}
		},
		"referenceFrames":{
			"melown2015": {
				"tileRange": [[0, 0 ],[0, 0 ]],
				"lodRange": [1,23]
			},
			"webmerc-projected": {
				"tileRange": [[0, 0 ],[1, 1 ]],
				"lodRange": [1,23]
			}

		}
	}
and in a different file

	{
	"comment" : "Automatically generated from \"NZ8mDEMv3.vrt\" raster dataset.",
	"credits" : 
	[
		"auto-a-href-http-data-linz-govt-nz-target-blank-sourced-from-linz-cc-by-4-0-a"
	],
	"definition" : 
	{
		"dataset" : "NZ8mDEMv3.vrt.2bf7234b02614d24f1f0f409322847eb",
		"geoidGrid" : "egm96_15.gtx",
    		"mask":"Nz.mask/mask",
		"introspection" : 
		{
			"position" : 
			[
				"obj",
				172.30182431502092,
				-40.846144869080661,
				"float",
				0,
				0,
				-90,
				0,
				1965639.7613371392,
				45
			]
		}
	},
	"driver" : "surface-dem",
	"group" : "linz",
	"id" : "NZ8mDEMv3masked",
	"referenceFrames" : 
	{
		"melown2015" : 
		{
			"lodRange" : [ 5, 21 ],
			"tileRange" : 
			[
				[ 15, 9 ],
				[ 15, 10 ]
			]
		}
	},
	"registry" : 
	{
		"credits" : 
		{
			"auto-a-href-http-data-linz-govt-nz-target-blank-sourced-from-linz-cc-by-4-0-a" : 
			{
				"copyrighted" : false,
				"id" : 32773,
				"notice" : "<a href=http://data.linz.govt.nz target=_blank>Sourced from LINZ. CC BY 4.0</a>"
			}
		}
	},
	"revision" : 0,
	"type" : "surface"
	}

**Comment by vaclavblazek** [comment]
Oh, stupid me. :man_facepalming: 

This mask file is per-reference frame. If you have `mask=Nz.mask/mask` then you need to have file `Nz.mask/mask.REFERENCE-FRAME` for every reference frame you specify in the resource, i.e. `Nz.mask/mask.melown2015` and `Nz.mask/mask.webmerrc-projected` in your case.

The one you generated is for `melown2015`, so just rename it to `mask.melown2015`. If you need the `webmerc-projected` version (in the case of `linz/lds-ophoto4` dataset), then generate another mask for `--referenceFrame=webmerc-projected` and place it as `mask.webmerc-projected`. NB: the file is pure quadtree raster mask with not notion of reference frame, so care must be taken to not swap them.

**Comment by jrjdavidson** [comment]
I changed the filename to `mask.melown2015` and updated the resoucre json file. I get the following in the log:
```
2021-09-14 20:15:34 I2 [1059(prepare:2)]: Preparing <melown2015/linz/lds-ophoto4>. {tms-raster-remote.cpp:prepare_impl():89}
2021-09-14 20:15:34 E2 [1059(prepare:2)]: gdal error 4: `/var/vts/mapproxy/datasets/Nz.mask/mask.melown2015' not recognized as a supported file format. {geodataset.cpp:GDALErrorHandler():77}
2021-09-14 20:15:34 E2 [1059(prepare:2)]: Failed to open dataset "/var/vts/mapproxy/datasets/Nz.mask/mask.melown2015". {geodataset.cpp:open():297}
2021-09-14 20:15:34 W2 [1059(prepare:2)]: Failed to prepare generator for <melown2015/linz/lds-ophoto4> (Failed to open dataset "/var/vts/mapproxy/datasets/Nz.mask/mask.melown2015". @{geodataset.cpp:open():297}); removing from set of known generators. {generators.cpp:operator()():203}
2021-09-14 20:15:34 E2 [1059(prepare:1)]: gdal error 4: `/var/vts/mapproxy/datasets/Nz.mask/mask.melown2015' not recognized as a supported file format. {geodataset.cpp:GDALErrorHandler():77}
2021-09-14 20:15:34 E2 [1059(prepare:1)]: Failed to open dataset "/var/vts/mapproxy/datasets/Nz.mask/mask.melown2015". {geodataset.cpp:open():297}
2021-09-14 20:15:34 W2 [1059(prepare:1)]: Failed to prepare generator for <webmerc-projected/linz/lds-ophoto4> (Failed to open dataset "/var/vts/mapproxy/datasets/Nz.mask/mask.melown2015". @{geodataset.cpp:open():297}); removing from set of known generators. {generators.cpp:operator()():203}
```

**Comment by vaclavblazek** [comment]
No, you still put extension-less name in the definition, so only `Nz.mask/mask`, the extension is added by mapproxy. (Now to looks for `Nz.mask/mask.melown2015.melown2015` which is not found and switches to raster-based mask.)

**Comment by jrjdavidson** [comment]
It works! I got an error due to the webmerc projection, however it didn't make sense to have it there as the path would be different for webmerc anyways, so I just removed it.

It would be handy if the ```mapproxy-rf-mask``` tool appended the *.melown2015 filename automatically based on the --lod tag?
Also - anything I can do to help with the documentation?
