### ISSUE TITLE
cdn down?

### ISSUE THREAD

**Issue by jrjdavidson** [Melown/vts-backend#34]
```
Ign:6 https://cdn.melown.com/packages/repos melown-bionic/ InRelease
Err:7 https://cdn.melown.com/packages/repos melown-bionic/ Release
  404  Not Found [IP: 43.229.60.229 443]
Reading package lists... Done
E: The repository 'https://cdn.melown.com/packages/repos melown-bionic/ Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by vaclavblazek** [comment]
Sorry, we were moving our CND to another machines and I moved only the `focal` repo there. I've synced `bionic` repo as well, pls give it a try.

**Comment by jrjdavidson** [comment]
Sorted. I should really upgrade that server to 20.04

Looks like 22.04 is out, any plans on creating a package for that ?

**Comment by vaclavblazek** [comment]
>Looks like 22.04 is out, any plans on creating a package for that ?
Slowly in progress, I ported some dependencies but had not much time for it.
