### ISSUE TITLE
Instructions are out of date.  Current method to build doesn't work:

### ISSUE THREAD

**Issue by maka-io** [Melown/vts-backend#5]
![vts-backend-broke](https://user-images.githubusercontent.com/3743882/45237349-65646f00-b2ac-11e8-9e82-ce203f0b2c67.PNG)

**Comment by vaclavblazek** [comment]
Thank you for reporting. I've fixed the instructions. I'll repeat it here:
```
cd vts-backend/vts-backend
make deb
```
i.e. you have to descend into project and then into the `vts-backend` directory and run `make deb` which generated a debian package.

However, is this really what you want? This repository is intended only for debian packaging, there is nothing to directly build nor install. This package depends on mapproxy, vtsd and tools, configures the infrastructure and provides some sample data.

We provid pre-built debian packages here: https://cdn.melown.com/packages/, you only need to add our repository to package lists and install the `vts-backend` debian package.

**Comment by maka-io** [comment]
That was it! Thanks @vaclavblazek !
