### ISSUE TITLE
Docker Install Requires gdal-abi-2-1-3?

### ISSUE THREAD

**Issue by xycarto** [Melown/vts-backend#8]
When preforming your standard Docker build:

```docker build -t vts-vtsd:latest -f docker/vtsd/Dockerfile .```  

I am met with the error:

```The following packages have unmet dependencies:
 vts-tools : Depends: gdal-abi-2-1-3 but it is not installable
             Depends: libgdal20 (>= 2.0.1) but it is not going to be installed
             Depends: libgomp1 (>= 4.9) but it is not going to be installed
             Depends: libopencv-highgui2.4v5 but it is not going to be installed
 vts-vtsd : Depends: gdal-abi-2-1-3 but it is not installable
            Depends: libgdal20 (>= 2.0.1) but it is not going to be installed
            Depends: libopencv-highgui2.4v5 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c apt-get update &&     apt-get -y install software-properties-common apt-transport-https     wget && add-apt-repository ppa:ubuntugis/ppa &&     cd /etc/apt/sources.list.d/ &&     wget http://cdn.melown.com/packages/conf/melown-xenial.list &&     wget -O - http://cdn.melown.com/packages/keys/oss.packages%40melown.com.key | apt-key add - && apt-get update &&     apt-get -y install vts-tools vts-vtsd && apt-get clean' returned a non-zero code: 100
```

I have successfully completed:

```git clone --recursive https://github.com/Melown/vts-backend.git ```
```cd vts-backend/vts-backend```
```make deb```

Do I need to add a specific GDAL package to the Docker build?

**Comment by vaclavblazek** [comment]
Unfortunately, docker support is non-maintained. It was written for Ubintu 16.04 and never updated. We use debian packages directly.

gdal-abi-* is a virtual package provided by particular libgdal package.

You can try to add proper package repository from http://cdn.melown.com/packages/ in the docker file.

**Comment by xycarto** [comment]
Thank you for the heads up :) I suspected that was the case, but thought I would check anyhow.

I downloaded the two Docker containers from Docker hub in the meantime and will look into building the containers on the upgraded version of Ubuntu in the future and try to get vtsd and Mapproxy Dockers working on the newer platforms.  I got this working so far: https://github.com/xycarto/xycarto_code/blob/master/scripts/docker/vts-geospatial/Dockerfile

Thanks for getting back to me so quickly
